language: node_js
node_js: stable

branches:
  only:
    - master

before_install:
  - git clone --depth 1 https://github.com/ahonn/blog.git
  - cd blog
  - npm install --global yarn

install:
  - yarn install

after_success:
  - git config --global user.name "ahonn"
  - git config --global user.email "ahonn95@outlook.com"
  - yarn run deploy
