language: node_js
node_js: stable

branches:
  only:
    - master

before_install:
  - git clone -b master --depth 1 https://github.com/ahonn/blog.git blog
  - cd blog

install:
  - npm install

after_success:
  - git config --global user.name "ahonn"
  - git config --global user.email "ahonn95@outlook.com"
  - sed -i "s/<token>/${GH_TOKEN}/g" ./_config.yml
  - yarn run publish
