language: node_js
node_js: stable

branches:
  only:
    - master

before_install:
  - npm install --global yarn
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: gh-pages
  on:
    branch: master
