owner: ahonn
repo: blog

site:
  author: Ahonn
  title: Ahonn's Blog
  description: Ahonn 的个人博客
  url: https://www.ahonn.me
  since: 2015
  icon: /static/images/icon.png
  rss: /atom.xml
  about: 59

social:
  twitter: ahonnjiang

theme:
  color: "#DB1105"

menu:
  - name: 归档
    url: /archives
  - name: 关于我
    url: /about
